"""Build delivery images without changing originals. Run with Python + Pillow.

The manifest serves static HTML srcsets and the interactive photo previews.
Only assets actually used by the page are included; no image is upscaled.
"""
import hashlib
import json
import re
from pathlib import Path

from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parents[1]
sources = set()
for name in ("index.html", "assets/js/beyond-work-stories.js", "assets/js/beyond-work-travel.js"):
    sources.update(re.findall(r'assets/img/(?!optimized/)[^\s\"\'<>]+\.(?:jpg|png)', (ROOT / name).read_text(encoding="utf-8")))
sources.add("assets/img/cat.png")
manifest = {}
for source in sorted(sources):
    path = ROOT / source
    with Image.open(path) as original:
        image = ImageOps.exif_transpose(original)
        image = image.convert("RGBA" if "A" in image.getbands() else "RGB")
        sizes = sorted({min(width, image.width) for width in (480, 960, 1440)})
        variants = []
        for width in sizes:
            relative = Path(source).relative_to("assets/img")
            output = Path("assets/img/optimized") / relative.parent / f"{relative.stem}-{width}.webp"
            target = ROOT / output
            target.parent.mkdir(parents=True, exist_ok=True)
            resized = image.resize((width, round(image.height * width / image.width)), Image.Resampling.LANCZOS)
            options = {"quality": 84, "method": 6}
            if original.info.get("icc_profile"):
                options["icc_profile"] = original.info["icc_profile"]
            resized.save(target, "WEBP", **options)
            variants.append({"src": output.as_posix(), "width": width, "bytes": target.stat().st_size})
        manifest[source] = {"width": image.width, "height": image.height,
                            "originalBytes": path.stat().st_size,
                            "originalSha256": hashlib.sha256(path.read_bytes()).hexdigest(), "variants": variants}

output = ROOT / "assets/js/image-assets.js"
output.write_text("// Generated by tools/prepare-images.py; originals remain unchanged.\nwindow.SITE_IMAGE_ASSETS = " + json.dumps(manifest, ensure_ascii=False, separators=(",", ":")) + ";\n", encoding="utf-8")
print(f"Prepared {len(manifest)} originals / {sum(len(x['variants']) for x in manifest.values())} delivery images")
